"""
LTspiceExporter — konwertuje Circuit → plik .cir dla LTspice XVII.

Obsługuje: Resistor, Capacitor, Inductor, VoltageSource, ACVoltageSource,
           OpAmp (VCVS E-element), BJT, Comparator.
"""
import os
import logging
from typing import Callable, Dict, List, Union
from solver_sch.model.circuit import (
    Circuit, Resistor, Capacitor, Inductor,
    VoltageSource, ACVoltageSource, CurrentSource,
    Diode, _BJTBase, BJT, BJT_N, BJT_P,
    MOSFET_N, MOSFET_P, OpAmp, Comparator, LM5085Gate,
)

logger = logging.getLogger(__name__)

# ── Per-component SPICE line formatters ───────────────────────────────────────

def _fmt_resistor(c: Resistor) -> str:
    return f"R{c.name} {c.node1} {c.node2} {c.resistance}"

def _fmt_capacitor(c: Capacitor) -> str:
    return f"C{c.name} {c.node1} {c.node2} {c.capacitance}"

def _fmt_inductor(c: Inductor) -> str:
    return f"L{c.name} {c.node1} {c.node2} {c.inductance}"

def _fmt_vsource(c: VoltageSource) -> str:
    return f"V{c.name} {c.node1} {c.node2} DC {c.voltage}"

def _fmt_acsource(c: ACVoltageSource) -> str:
    return (
        f"V{c.name} {c.node1} {c.node2} "
        f"SINE({c.dc_offset} {c.amplitude} {c.frequency}) "
        f"AC {c.ac_mag} {c.ac_phase}"
    )

def _fmt_isource(c: CurrentSource) -> str:
    return f"I{c.name} {c.node1} {c.node2} {c.current}"

def _fmt_opamp(c: OpAmp) -> str:
    return f"E{c.name} {c.out} 0 {c.in_p} {c.in_n} {c.gain}"

def _fmt_diode(c: Diode) -> str:
    model_name = getattr(c, "model", None) or "D_MODEL"
    return f"D{c.name} {c.anode} {c.cathode} {model_name}"

def _fmt_bjt(c: "_BJTBase") -> str:
    default_model = "NPN_MODEL" if isinstance(c, BJT_N) else "PNP_MODEL"
    model_name = getattr(c, "model", None) or default_model
    return f"Q{c.name} {c.collector} {c.base} {c.emitter} {model_name}"

def _fmt_mosfet(c: Union[MOSFET_N, MOSFET_P]) -> str:
    default_model = "NMOS_MODEL" if isinstance(c, MOSFET_N) else "PMOS_MODEL"
    model_name = getattr(c, "model", None) or default_model
    w = getattr(c, "w", 1e-6)
    l = getattr(c, "l", 1e-6)
    return f"M{c.name} {c.drain} {c.gate} {c.source} {c.source} {model_name} W={w} L={l}"

def _fmt_comparator(c: Comparator) -> str:
    return (
        f"B{c.name} {c.node_out} 0 "
        f"V=if(V({c.node_p})>V({c.node_n}), {c.v_high}, {c.v_low})"
    )

def _fmt_lm5085(c: LM5085Gate) -> List[str]:
    vref, vd, k = c.VREF, c.vdrive, c.k
    return [
        f"* U6 LM5085SD/NOPB — COT PFET Buck Controller (behavioral DC model)",
        f"* PGATE: V_pgate = V(vin) - {vd}*sigmoid({k}*(VREF={vref} - V(fb)))",
        (
            f"B{c.name}_GATE {c.pgate} {c.gnd} "
            f"V=V({c.vin})-{vd}*(0.5*(1+tanh({k/2}*({vref}-V({c.fb})))))"
        ),
        f"V{c.name}_VCC {c.vcc} {c.gnd} DC {c.VCC_VOLTAGE}",
    ]


_SPICE_FORMATTERS: Dict[type, Callable] = {
    Resistor:       _fmt_resistor,
    Capacitor:      _fmt_capacitor,
    Inductor:       _fmt_inductor,
    VoltageSource:  _fmt_vsource,
    ACVoltageSource: _fmt_acsource,
    CurrentSource:  _fmt_isource,
    OpAmp:          _fmt_opamp,
    Diode:          _fmt_diode,
    BJT_N:          _fmt_bjt,
    BJT_P:          _fmt_bjt,
    MOSFET_N:       _fmt_mosfet,
    MOSFET_P:       _fmt_mosfet,
    Comparator:     _fmt_comparator,
    LM5085Gate:     _fmt_lm5085,
}


class LTspiceExporter:
    """Konwertuje obiekt Circuit na format .cir dla LTspice."""

    @staticmethod
    def export(
        circuit: Circuit,
        filename: str,
        analysis: str = "op",           # "op" | "ac" | "tran"
        ac_start: float = 10,
        ac_stop: float = 100e3,
        ac_points: int = 20,            # dec points
        tran_stop: float = 10e-3,
        tran_step: float = 10e-6,
    ) -> str:
        """
        Eksportuje układ do pliku .cir i zwraca ścieżkę.

        Args:
            circuit:     Obiekt Circuit
            filename:    Ścieżka do pliku wyjściowego
            analysis:    Rodzaj analizy: "op" | "ac" | "tran"
            ac_start:    Początkowa częstotliwość AC [Hz]
            ac_stop:     Końcowa częstotliwość AC [Hz]
            ac_points:   Punkty na dekadę (dla .ac dec)
            tran_stop:   Czas końcowy tranzjentu [s]
            tran_step:   Krok czasu tranzjentu [s]

        Returns:
            Ścieżka bezwzględna do wygenerowanego pliku .cir
        """
        lines = [
            f"* LTspice Export: {circuit.name}",
            f"* Generated by SolverSCH",
            "",
        ]

        for comp in circuit.get_components():
            fmt = _SPICE_FORMATTERS.get(type(comp))
            if fmt:
                result = fmt(comp)
                if isinstance(result, list):
                    lines.extend(result)
                else:
                    lines.append(result)

        # ── Model definitions ──────────────────────────────────────
        lines.append("")
        
        # Base/Default fallback models logic
        lines.append(".model D_MODEL D(Is=1e-14 n=1)")
        lines.append(".model NPN_MODEL NPN(Bf=100 Vaf=50)")
        lines.append(".model PNP_MODEL PNP(Bf=100 Vaf=50)")
        lines.append(".model NMOS_MODEL NMOS(Kp=100e-6 Vto=1)")
        lines.append(".model PMOS_MODEL PMOS(Kp=50e-6 Vto=-1)")

        # Custom explicit models
        models = circuit.get_models()
        if models:
            lines.append("* Custom Models from Circuit Registry:")
            for model_name, model_card in models.items():
                lines.append(repr(model_card))

        # ── Analysis command ───────────────────────────────────────
        lines.append("")
        if analysis == "op":
            lines.append(".op")
        elif analysis == "ac":
            lines.append(f".ac dec {ac_points} {ac_start} {ac_stop}")
            lines.append(".op")
        elif analysis == "tran":
            lines.append(f".tran {tran_step} {tran_stop} 0 {tran_step}")
        else:
            # Pass custom string (e.g. from old LTspiceVerifier tests)
            lines.append(analysis)

        lines.append(".probe V(*) I(*)")
        lines.append(".save all")
        lines.append(".end")
        lines.append("")

        abs_path = os.path.abspath(filename)
        os.makedirs(os.path.dirname(abs_path) or ".", exist_ok=True)
        with open(abs_path, "w", encoding="ascii", errors="replace") as f:
            f.write("\n".join(lines))

        logger.info("[Exporter] Written: %s (%d lines)", abs_path, len(lines))
        return abs_path
