"""
LTspiceExporter — konwertuje Circuit → plik .cir dla LTspice XVII.

Obsługuje: Resistor, Capacitor, Inductor, VoltageSource, ACVoltageSource,
           OpAmp (VCVS E-element), BJT, Comparator.
"""
import os
import logging
from solver_sch.model.circuit import (
    Circuit, Resistor, Capacitor, Inductor,
    VoltageSource, ACVoltageSource,
    Diode, BJT, MOSFET_N, MOSFET_P, OpAmp, Comparator,
)

log = logging.getLogger(__name__)


class LTspiceExporter:
    """Konwertuje obiekt Circuit na format .cir dla LTspice."""

    @staticmethod
    def export(
        circuit: Circuit,
        filename: str,
        analysis: str = "op",           # "op" | "ac" | "tran"
        ac_start: float = 10,
        ac_stop: float = 100e3,
        ac_points: int = 20,            # dec points
        tran_stop: float = 10e-3,
        tran_step: float = 10e-6,
    ) -> str:
        """
        Eksportuje układ do pliku .cir i zwraca ścieżkę.

        Args:
            circuit:     Obiekt Circuit
            filename:    Ścieżka do pliku wyjściowego
            analysis:    Rodzaj analizy: "op" | "ac" | "tran"
            ac_start:    Początkowa częstotliwość AC [Hz]
            ac_stop:     Końcowa częstotliwość AC [Hz]
            ac_points:   Punkty na dekadę (dla .ac dec)
            tran_stop:   Czas końcowy tranzjentu [s]
            tran_step:   Krok czasu tranzjentu [s]

        Returns:
            Ścieżka bezwzględna do wygenerowanego pliku .cir
        """
        lines = [
            f"* LTspice Export: {circuit.name}",
            f"* Generated by SolverSCH",
            "",
        ]

        for comp in circuit.get_components():
            name = comp.name  # np. "R1", "Vin", "U1"

            if isinstance(comp, Resistor):
                # SPICE format: R<name> <n+> <n-> <value>
                lines.append(f"R{name} {comp.node1} {comp.node2} {comp.resistance}")

            elif isinstance(comp, Capacitor):
                lines.append(f"C{name} {comp.node1} {comp.node2} {comp.capacitance}")

            elif isinstance(comp, Inductor):
                lines.append(f"L{name} {comp.node1} {comp.node2} {comp.inductance}")

            elif isinstance(comp, VoltageSource):
                # DC source: V<name> <n+> <n-> <value>
                lines.append(f"V{name} {comp.node1} {comp.node2} DC {comp.voltage}")

            elif isinstance(comp, ACVoltageSource):
                # AC stimulus: SINE(offset amp freq) + AC magnitude
                lines.append(
                    f"V{name} {comp.node1} {comp.node2} "
                    f"SINE({comp.dc_offset} {comp.amplitude} {comp.frequency}) "
                    f"AC {comp.ac_mag} {comp.ac_phase}"
                )

            elif isinstance(comp, OpAmp):
                # Modelujemy jako VCVS (E-element): wyjście sterowane napięciem różnicowym
                # E<name> <out> <gnd> <in+> <in-> <gain>
                # Węzły OpAmp: in_n=op_inv, in_p=vcc lub 0, out=op_out
                lines.append(
                    f"E{name} {comp.out} 0 {comp.in_p} {comp.in_n} {comp.gain}"
                )

            elif isinstance(comp, Diode):
                model_name = getattr(comp, "model", None) or "D_MODEL"
                lines.append(f"D{name} {comp.anode} {comp.cathode} {model_name}")

            elif isinstance(comp, BJT):
                default_model = "NPN_MODEL" if getattr(comp, 'bjt_type', 'NPN') == 'NPN' else "PNP_MODEL"
                model_name = getattr(comp, "model", None) or default_model
                lines.append(
                    f"Q{name} {comp.collector} {comp.base} {comp.emitter} {model_name}"
                )

            elif isinstance(comp, (MOSFET_N, MOSFET_P)):
                default_model = "NMOS_MODEL" if isinstance(comp, MOSFET_N) else "PMOS_MODEL"
                model_name = getattr(comp, "model", None) or default_model
                lines.append(
                    f"M{name} {comp.drain} {comp.gate} {comp.source} {comp.source} {model_name}"
                )

            elif isinstance(comp, Comparator):
                # Behavioral voltage source
                lines.append(
                    f"B{name} {comp.node_out} 0 "
                    f"V=if(V({comp.node_p})>V({comp.node_n}), {comp.v_high}, {comp.v_low})"
                )

        # ── Model definitions ──────────────────────────────────────
        lines.append("")
        
        # Base/Default fallback models logic
        lines.append(".model D_MODEL D(Is=1e-14 n=1)")
        lines.append(".model NPN_MODEL NPN(Bf=100 Vaf=50)")
        lines.append(".model PNP_MODEL PNP(Bf=100 Vaf=50)")
        lines.append(".model NMOS_MODEL NMOS(Kp=100e-6 Vto=1)")
        lines.append(".model PMOS_MODEL PMOS(Kp=50e-6 Vto=-1)")

        # Custom explicit models
        models = circuit.get_models()
        if models:
            lines.append("* Custom Models from Circuit Registry:")
            for model_name, model_card in models.items():
                lines.append(repr(model_card))

        # ── Analysis command ───────────────────────────────────────
        lines.append("")
        if analysis == "op":
            lines.append(".op")
        elif analysis == "ac":
            lines.append(f".ac dec {ac_points} {ac_start} {ac_stop}")
            lines.append(".op")
        elif analysis == "tran":
            lines.append(f".tran {tran_step} {tran_stop} 0 {tran_step}")
        else:
            # Pass custom string (e.g. from old LTspiceVerifier tests)
            lines.append(analysis)

        lines.append(".probe V(*) I(*)")
        lines.append(".save all")
        lines.append(".end")
        lines.append("")

        abs_path = os.path.abspath(filename)
        os.makedirs(os.path.dirname(abs_path) or ".", exist_ok=True)
        with open(abs_path, "w", encoding="ascii", errors="replace") as f:
            f.write("\n".join(lines))

        log.info("[Exporter] Written: %s (%d lines)", abs_path, len(lines))
        return abs_path
